### PR TITLE
Storage discovery and update

### PR DESCRIPTION
**Pull request by PeterLackner**
I made an addition for storage discovery and value update.

### CODE REVIEW

**Review by takala-jp — COMMENTED** [review]
Thank you for contributing, let me review and test (have been offline for a bit and catching up on the backlog)

**Comment by takala-jp** [comment]
This looks like a great addition. When trying to import the Zabbix template I'm getting:

`Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(2)": the tag "snmp_community" is missing.`

**Comment by PeterLackner** [comment]
I made made the template in the GUI in version 5.4 in zabbix. In zabbix only the complete template can be exported not just the discovery rule I made. The resulting file was completely different to your version which was created for V3.0 of zabbix. I uploaded my complete template for reference.
Anyhow, it looks like "snmp_community" is used in your original file in several lines, but not in my template.

**Comment by takala-jp** [comment]
Ah yes, looks like 5.4 did not add the snmp tag. It would be good to keep the template compatible with at least Zabbix 4.0. How about you remove the templates from the PR, I'll merge your version of the script and I'll update the template to include storage while keeping it compatible with older zabbix versions?

Also, do you think it'd be worth it to make storage discovery/reporting optional via a "-s" parameter? Would allow someone to use the new script version without having to update their template.

**Comment by PeterLackner** [comment]
I removed the template.
The -s parameter is a good idea, are you going to make this?

**Comment by takala-jp** [comment]
If you have time and motivation it be great if you could do it 😇

**Comment by PeterLackner** [comment]
Should be OK now, without -s it behaves like before, with -s it does either the LLD or the value update depending on -d

**Comment by takala-jp** [comment]
Awesome, thank you 🙇 

I'll test and prepare the zabbix template this week.

**Comment by takala-jp** [comment]
Merged your PR, thank you again.

**Pull request merged**
