### PR TITLE
Fixed issue causing "non-zero exit status 2"

### PR DESCRIPTION
**Pull request by TUBEOF**
I had the same problem as in #26 
This would be a possible fix for it, which I already use without any problems.

### CODE REVIEW

**Comment by takala-jp** [comment]
Thank you for sharing that. 

Doesn't this mask the issue rather than fix it though? The underlying issue is that zabbix returns 2 instead of the expected 0. It would be good to know why.

Having said that, run() seems to be the recommended approach. What happens if you call it with `capture_output=True`?

**Comment by TUBEOF** [comment]
I can't say exactly what the reason for the status code 2 is.
However, I have tested something with zabbix_sender myself and have often received the status code 2 there without there being a real problem.

So I strongly assume that this is a problem with zabbix_sender.

**Comment by takala-jp** [comment]
Interesting, based on the current evidence it seems that this is one of those cases.  I'll test the change on my local environments before merging the PR. Thank you for contributing.

**Comment by chrisgassen** [comment]
I also "fixed" it with this solution and added a "capture output" + if to still get all other errorcodes: b4bec8ee207fdcc13b4d50b4de5397b3beda481f

**Comment by takala-jp** [comment]
Thank you for reporting, debugging and finding a solution for this issue @TUBEOF and @chrisgassen. I don't believe that silently ignoring errors is the correct answer. I have adopted the subprocess.run method as per this PR but added a parameter to ignore zabbix_sender errors. The default behavior of the script won't change but you can now easily handle them while still being able to capture the output.

**Pull request closed without merging**
